# Generated by Django 2.2.13 on 2020-07-14 12:57

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instalacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CamaraZona',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('id_camara_zona', models.CharField(default='', max_length=255)),
                ('descripcion', models.CharField(default='', max_length=250)),
                ('camara_zona_estado', models.BooleanField(default=True)),
                ('id_instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instalacion.Instalacion')),
            ],
        ),
    ]
