# Generated by Django 2.2.13 on 2020-08-30 15:56

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CamaraZona',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('id_camara_zona', models.CharField(default='', max_length=255)),
                ('descripcion', models.CharField(default='', max_length=250)),
                ('camara_zona_estado', models.BooleanField(default=True)),
            ],
        ),
    ]
