# Generated by Django 2.2.13 on 2020-09-18 01:43

from django.db import migrations, models
import djongo.models.fields
import espacios.models
import instalacion.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Espacios',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('instalacion', djongo.models.fields.EmbeddedField(blank=True, model_container=instalacion.models.InstalacionEmbebido, null=True)),
                ('descripcion', models.CharField(default='', max_length=250)),
                ('zonas_camara', djongo.models.fields.ArrayField(blank=True, model_container=espacios.models.ZonaCamara, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'espacios',
            },
        ),
    ]
