# Generated by Django 2.2.13 on 2020-11-26 03:26

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsoRed',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('enviadosGB', models.FloatField(blank=True, default=0.0)),
                ('recibidosGB', models.FloatField(blank=True, default=0.0)),
                ('tipo_red', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'uso_red',
            },
        ),
    ]
