# Generated by Django 2.2.13 on 2020-09-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camaras',
            name='snapshot',
            field=models.CharField(default='', max_length=250),
        ),
    ]
