# Generated by Django 2.2.13 on 2020-12-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0002_camaras_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='camaras',
            name='imagen_defecto',
            field=models.CharField(default='', max_length=250),
        ),
    ]
