# Generated by Django 2.2.13 on 2020-09-08 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instalacion', '0001_initial'),
        ('cliente', '0001_initial'),
        ('app', '0002_auto_20200828_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id_cliente',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.Cliente'),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_instalacion',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instalacion.Instalacion'),
        ),
    ]
