# Generated by Django 2.2.13 on 2020-07-14 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nif', models.CharField(default='', max_length=20)),
                ('razon_social', models.CharField(default='', max_length=255)),
                ('direccion', models.CharField(default='', max_length=255)),
                ('poblacion', models.CharField(default='', max_length=255)),
                ('provincia', models.CharField(default='', max_length=255)),
                ('codigo_postal', models.CharField(default='', max_length=10)),
                ('telefono', models.CharField(default='', max_length=20)),
                ('movil', models.CharField(default='', max_length=20)),
                ('email', models.CharField(default='', max_length=255)),
                ('administracion_nombre', models.CharField(default='', max_length=255)),
                ('administracion_cargo', models.CharField(default='', max_length=255)),
                ('administracion_telefono', models.CharField(default='', max_length=20)),
                ('administracion_movil', models.CharField(default='', max_length=20)),
                ('administracion_email', models.CharField(default='', max_length=255)),
                ('tecnico_nombre', models.CharField(default='', max_length=255)),
                ('tecnico_cargo', models.CharField(default='', max_length=255)),
                ('tecnico_telefono', models.CharField(default='', max_length=20)),
                ('tecnico_movil', models.CharField(default='', max_length=20)),
                ('tecnico_email', models.CharField(default='', max_length=255)),
                ('cliente_estado', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
