# Generated by Django 2.2.13 on 2020-08-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='administracion_email',
            field=models.EmailField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tecnico_email',
            field=models.EmailField(default='', max_length=255),
        ),
    ]
