# Generated by Django 2.2.13 on 2020-08-24 20:32

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AforoInfo',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nro_aforo', models.IntegerField(blank=True, default=0)),
                ('cola', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'db_table': 'aforo_info',
            },
        ),
    ]
