# Generated by Django 2.2.13 on 2021-03-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectsDetector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objects',
            name='label',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
