# Generated by Django 2.2.13 on 2020-09-20 22:56

import camaras_historico.models
from django.db import migrations, models
import djongo.models.fields
import instalacion.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myCamaras',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('instalacion', djongo.models.fields.EmbeddedField(blank=True, model_container=instalacion.models.InstalacionEmbebido, null=True)),
                ('nombre_camara', models.CharField(default='', max_length=250)),
                ('serial_camara', models.CharField(default='', max_length=250)),
                ('ts', models.TimeField()),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('zonas_camara', djongo.models.fields.ArrayField(blank=True, model_container=camaras_historico.models.ZonaCamara, null=True)),
            ],
            options={
                'db_table': 'camaras_historico',
            },
        ),
    ]
