# Generated by Django 2.2.13 on 2020-12-09 22:13

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CamarasHistorico',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=250)),
                ('network_meraky_id', models.CharField(default='', max_length=255)),
                ('nif_cliente', models.CharField(default='', max_length=255)),
                ('nombre_camara', models.CharField(default='', max_length=250)),
                ('serial_camara', models.CharField(default='', max_length=250)),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('nombre_zona_camara', models.CharField(default='', max_length=250)),
                ('nro_personas', models.IntegerField(default=0)),
                ('suma_total_aforo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'camaras_historico',
            },
        ),
    ]
