# Generated by Django 2.2.13 on 2020-08-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='color_barra_cabecera',
            field=models.CharField(choices=[('WTH', 'Blanco'), ('G30', 'Gris 30'), ('G60', 'Gris 60'), ('BLK', 'Negro')], default='BLK', max_length=3),
        ),
    ]
