# Generated by Django 2.2.13 on 2020-12-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacion',
            name='network_meraky_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
