# Generated by Django 2.2.13 on 2020-09-04 11:32

from django.db import migrations, models
import djongo.models.fields
import instalacion.forms
import instalacion.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fondos',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('instalacion', djongo.models.fields.EmbeddedField(blank=True, model_container=instalacion.models.InstalacionEmbebido, model_form_class=instalacion.forms.InstalacionEmbebidoForm, null=True)),
                ('descripcion', models.CharField(default='', max_length=255)),
                ('orientacion', models.CharField(default='', max_length=20)),
                ('url_verde', models.CharField(default='', max_length=255)),
                ('nombre_archivo_verde', models.CharField(default='', max_length=255)),
                ('url_ambar', models.CharField(default='', max_length=255)),
                ('nombre_archivo_ambar', models.CharField(default='', max_length=255)),
                ('url_rojo', models.CharField(default='', max_length=255)),
                ('nombre_archivo_rojo', models.CharField(default='', max_length=255)),
                ('url_cerrado', models.CharField(default='', max_length=255)),
                ('nombre_archivo_cerrado', models.CharField(default='', max_length=255)),
                ('hora_apertura', models.TimeField()),
                ('hora_cierre', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'fondos',
            },
        ),
    ]
