# Generated by Django 2.2.13 on 2020-11-29 22:13

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariosRed',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nro_usuarios_ethernet', models.IntegerField(blank=True, default=0)),
                ('nro_usuarios_wifi', models.IntegerField(blank=True, default=0)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarios_red',
            },
        ),
    ]
