# Generated by Django 2.2.13 on 2020-12-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_red', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariosred',
            name='network_meraky_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
