# Generated by Django 2.2.13 on 2021-03-17 13:48

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSettings',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('email', models.EmailField(default='', max_length=255)),
                ('objectsDetection', models.BooleanField(default=False)),
                ('maskDetection', models.BooleanField(default=False)),
                ('thresholdValue', models.DecimalField(decimal_places=2, default=0.5, max_digits=2)),
                ('smoothValue', models.IntegerField(default=1)),
                ('settings_date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'streaming_settings',
            },
        ),
        migrations.AddField(
            model_name='streaming',
            name='label',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='streaming',
            name='mask',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='streaming',
            name='personid',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
